// Emits the contract's string enums as runtime arrays, because openapi-typescript only produces
// *types* and a select needs the values (D2.15: the UI never hand-writes what the spec describes).
// Run through `npm run generate:api`; `--check` fails when the committed output is stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const contractPath = fileURLToPath(
  new URL('../../orchestrator/contracts/openapi/oms-core.json', import.meta.url)
)
const outPath = fileURLToPath(new URL('../src/api/enums.gen.ts', import.meta.url))
const check = process.argv.includes('--check')

const spec = JSON.parse(readFileSync(contractPath, 'utf8'))

function queryEnum(path, name) {
  const param = spec.paths[path].get.parameters.find((p) => p.name === name)
  if (!param?.schema?.enum) {
    throw new Error(`${path} ?${name} is no longer an enum in the contract`)
  }
  return param.schema.enum
}

function schemaEnum(schema, property) {
  const values = spec.components.schemas[schema]?.properties?.[property]?.enum
  if (!values) {
    throw new Error(`${schema}.${property} is no longer an enum in the contract`)
  }
  return values
}

const entries = [
  ['ATTRIBUTE_UNITS', schemaEnum('AttributeResponse', 'unit')],
  ['AUDIT_ENTITY_TYPES', queryEnum('/api/admin/audit-entries', 'entityType')],
  ['AUDIT_ACTIONS', queryEnum('/api/admin/audit-entries', 'action')],
]

const body =
  '// GENERATED by scripts/generate-enums.mjs from the OpenAPI contract — do not edit.\n\n' +
  entries
    .map(
      ([name, values]) =>
        `export const ${name} = [\n${values.map((v) => `  ${JSON.stringify(v)},`).join('\n')}\n] as const\n`
    )
    .join('\n')

if (check) {
  let current = ''
  try {
    current = readFileSync(outPath, 'utf8')
  } catch {
    // missing counts as stale
  }
  if (current.replace(/\r\n/g, '\n') !== body) {
    console.error('src/api/enums.gen.ts is not up-to-date — run `npm run generate:api`')
    process.exit(1)
  }
} else {
  writeFileSync(outPath, body)
}
